trigger:
  branches:
    include:
      - main  # Se ejecutará cuando haya cambios en la rama main

pool:
  vmImage: 'windows-latest'  # Usa Windows para compatibilidad con .NET

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build'

- script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/publish'
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureServiceConnection'  # Nombre de la conexión a Azure
    appType: 'webApp'  # Especifica que es un App Service de tipo Web App
    appName: 'apidevopsdocker'  # Reemplázalo con el nombre de tu App Service
    package: '$(Build.ArtifactStagingDirectory)/publish'
