trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/Functions/**

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
  - task: UseDotNet@2
    displayName: Setup .NET 8
    inputs:
      packageType: sdk
      version: 8.0.x

  - task: DotNetCoreCLI@2
    displayName: Publish Functions
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/Functions/Functions.csproj
      arguments: >
        -c $(buildConfiguration)
        -o $(Build.ArtifactStagingDirectory)/functions

  - task: AzureFunctionApp@2
    displayName: Deploy to Azure Functions
    inputs:
      azureSubscription: sc-solicitudesapp
      appType: functionAppLinux
      appName: func-solicitudesapp
      package: $(Build.ArtifactStagingDirectory)/functions
