trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/**
      - Dockerfile

pool:
  vmImage: ubuntu-latest

variables:
  acrName: acrsolicidesapp
  imageName: api-solicitudesapp

steps:
  - task: Docker@2
    displayName: Build and push Docker image
    inputs:
      containerRegistry: sc-acr-solicitudesapp
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: Dockerfile
      buildContext: .
      tags: |
        $(Build.BuildId)
        latest

  - task: AzureWebAppContainer@1
    displayName: Deploy container to App Service
    inputs:
      azureSubscription: sc-solicitudesapp
      appName: api-solicitudesapp
      containers: $(acrName).azurecr.io/$(imageName):$(Build.BuildId)
